### ISSUE TITLE
How to start ? 

### ISSUE THREAD

**Issue by YouAreBest** [uber/AthenaX#16]
In situations where documentation is extremely scarce .  
I try to build environment via http://athenax.readthedocs.io/en/latest/getting_started
But can't find the com. Foo. MyCatalogProvider, I don't find this class, also does not have the detailed case can refer to .
I think detailed documentation is required for open source projects.
thank you

**Comment by walterddr** [comment]
you are absolutely right. We are actually moving to Flink 1.5 TableSourceFactory approach as of now. many of our users do find this very confusing

**Comment by walterddr** [comment]
close as duplicate of https://github.com/uber/AthenaX/issues/4
