### ISSUE TITLE
can not find  com.uber.athenax.backend.api ?

### ISSUE THREAD

**Issue by runc** [uber/AthenaX#39]
clone the project,but can not find com.uber.athenax.backend.api ,such as 
import com.uber.athenax.backend.api.JobDefinition;
import com.uber.athenax.backend.api.JobsApiService;
import com.uber.athenax.backend.api.NotFoundException;

**Comment by walterddr** [comment]
you need to use maven build or setting up your intellij to generate source from the swagger API configuration files. See https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin for more info

**Comment by runc** [comment]
mvn clean generate-sources
