### ISSUE TITLE
Current status of AthenaX

### ISSUE THREAD

**Issue by link3280** [uber/AthenaX#42]
Hi,  I'd like to try out AthenaX and I'm interested in the current status of AthenaX since the last commit is almost a year ago. Is the project still maintained by Uber? And is there any future plan, such as supporting higher versions of Flink?

**Comment by walterddr** [comment]
Hi @link3280. unfortunately `uber/AthenaX` has been drift off Uber's in-house implementation for a while and we are planning to open-source the components in a separate repo which include most of our advance features like resource estimation and automatic monitoring system. Please stay tune.

**Comment by link3280** [comment]
@walterddr Thanks for the update. I'm wondering if we should first start with AthenaX or just wait for the new one (we are planning to start in a month). May I ask for your advice? Thanks a lot!

**Comment by walterddr** [comment]
we do not have plan to release any component in a month unfortunately

**Comment by link3280** [comment]
Get it. Thanks for the information :)
